= {documentation}[Parking Bill]
:author:        Edwyn Tech
:owner:         Edwyntech
:email:         mailto:contact@edwyn.tech
:project:       parking-bill
:key:           {owner}_{project}
:repo:          https://github.com/{owner}/{project}
:documentation: https://{owner}.github.io/{project}
:cicd:            {repo}/actions/workflows/cicd.yaml
:linkedin:      https://www.linkedin.com/company/74937487/
:youtube:       https://www.youtube.com/@EdwynTech
:twitch:        https://www.twitch.tv/edwyntech
:badges:        https://img.shields.io/badge

image:{cicd}/badge.svg[link={cicd},window=_blank]

Parking bill calculation and generation.

== Structure

Ce projet est construit comme un projet Maven multi-module basé sur le JDK 21.

Parmi ces modules :

* `domain` - Les fonctions de l'application.
* `documentation` - la documentation vivante du projet.
* `application` - l'application bureau (JavaFX).

[NOTE]
====
Les répertoires qui démarrent par un point contiennent des configurations additionnelles :

* `.github` - configure le CICD
* `.idea` - configure IntelliJ
* `.mvn` - configure la toolchain Maven
====

== Cycle De Vie

|===

|Construction|mvn install
|Documentation|mvn verify
|Lancement|mvn spring-boot:run
|===

== Auteur

image::https://img.shields.io/badge/Par_email-email?style=social&logo=microsoftoutlook&label={author}[link={email}]
image::{badges}/Sur_LinkedIn-email?style=social&logo=linkedin&label={author}[link={linkedin},window=_blank]
image::https://img.shields.io/badge/Youtube-channel?style=social&logo=youtube&label={author}[link={youtube},window=_blank]
image::https://img.shields.io/badge/Twitch-channel?style=social&logo=twitch&label={author}[link={twitch},window=_blank]
